### ISSUE TITLE
Finished jobs stuck in status Terminating with K8s 1.22 job-tracking

### ISSUE THREAD

**Issue by gi8lino** [k8up-io/k8up#554] opened 2021-11-17 16:37 UTC
### Description

hi

sometimes jobs (backup, prunes and checks), stuck in status Terminating.
If I manually delete the job, the job will be delete, but the corresponding pod doesn't.
If I delete the finalizer of the pod, the pod then will be deleted.

### Additional Context

Pods get spawned with the `batch.kubernetes.io/job-tracking` finalizer, which is a feature gate from K8s 1.22 (https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-tracking-with-finalizers)

### Expected Behavior

If a job is finished and the successfulJobsHistoryLimit or failedJobsHistoryLimit is reached, the job and the pod should be deleted

### Version of K8up

v2.0.1

### Version of Kubernetes

v1.22.3+k3s1

### Distribution of Kubernetes

k3s

**Comment by ccremer** [comment] 2021-12-03 08:21
Can you elaborate which finalizer you mean? K8up shouldn't add finalizers to pods, only jobs.

**Comment by gi8lino** [comment] 2021-12-03 19:03
the finalizer is `batch.kubernetes.io/job-tracking`.
i have other jobs, but only the jobs created by k8up stuck sometime...

**Comment by ccremer** [comment] 2021-12-04 10:11
Thanks for mentioning it.
So I did read up on that finalizer here: https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-tracking-with-finalizers

This job-tracking is a Kubernetes 1.22 Alpha feature that must be explicitly enabled as a feature gate on the API server.
K8up generally doesn't support alpha features. I don't know what would have to be done to fix this, resp. whether this something that can be fixed within K8up or simply due to the Alpha state of Kubernetes itself. I'm afraid you'll have to investigate this on your own.

If you can find the root cause of this issue and can pinpoint to K8up, please suggest possible fixes.

**Comment by Kidswiss** [comment] 2022-02-28 14:50
Hi @gi8lino 

Is this still an issue with Kubernetes 1.23? The feature is now beta.

Best Regards

**Comment by gi8lino** [comment] 2022-02-28 14:56
hi @Kidswiss 

No, it doesn't happen again.

Regards

**Comment by Kidswiss** [comment] 2022-02-28 15:09
Hi @gi8lino 

Cool! Thanks for the feedback! Then it was probably some alpha quirck.

I'm closing here. Thanks for contributing.

Best Regards
Simon

**Closed by Kidswiss** 2022-02-28 15:09 UTC
Labels: bug, help wanted
