### ISSUE TITLE
job labels

### ISSUE THREAD

**Issue by gi8lino** [k8up-io/k8up#571] opened 2021-11-29 13:48 UTC
### Summary

**As** a console cowboy🤠
**I want** a feature
**So that** I can define a custom label for all jobs or eacht job type. 

### Context

Currently the label will be generated, ex `job-name: backup-healthchecks-backup-gwn9w`.
I use cilium and it cannot check for wildcard label values, it can only check for the labels "key" or an explicit label.

**Comment by ccremer** [comment] 2021-11-30 15:31
Hi
Just to get more details: Do you require a specific, static label with predictable values or do you need to be able to set custom label key/value paris for your cilium case?

**Comment by gi8lino** [comment] 2021-11-30 16:51
hi @ccremer 
For me a static label with a predictable value is ok.
ex: `job-name: k8up` would be fine.

Do you have an idea how to limit access to minio for k8up jobs in cilium?

**Comment by ccremer** [comment] 2021-11-30 17:53
You're in luck, with https://github.com/k8up-io/k8up/pull/570 released in v2.1.0 just recently you'll get a static label  `k8upjob: true`. It was actually present in v1.x, but a regression bug since the v2 release.

I'm personally not that familiar with Cilium unfortunately.
Maybe @glrf knows more?

**Comment by gi8lino** [comment] 2021-11-30 18:01
I am also happy with the label `k8upjob: true`.

**Comment by glrf** [comment] 2021-12-06 15:56
I'm not quite sure what you mean by 
> Do you have an idea how to limit access to minio for k8up jobs in cilium?

With the static label you should be able to write a policy to match k8up jobs. (BTW: If you don't now already [the policy editor](https://editor.cilium.io/) is very helpful when writing cilium network policies).

**Comment by ccremer** [comment] 2021-12-06 16:14
Closing the issue as further Cilium support is out-of-scope here.
There's also the Cilium docs: https://docs.cilium.io/en/v1.10/

**Closed by ccremer** 2021-12-06 16:14 UTC
Labels: enhancement
