### ISSUE TITLE
backup error :   [controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.                                                                                                            │

### ISSUE THREAD

**Issue by LandiLorenzo** [k8up-io/k8up#986] opened 2024-07-03 13:54 UTC
### Description

In a schedule, the resultant backup goes in runtime go error.
 the identical configuration works for other databases. The only difference is the database size is like 1.5Gb, the others are like 100/200Mb.
pod log attached. 
the backup file is present in the restic repository after the execution, it seems all good. How to get rid of this error? 
[err.pod.log](https://github.com/user-attachments/files/16085881/err.pod.log)

### Additional Context

It's a backup with prebackuppod, and the storage is private s3 endpoint. 

### Expected Behavior

to not have an error

### Version of K8up

v2.10.0

### Version of Kubernetes

1.29

### Distribution of Kubernetes

Kind

**Comment by croissong** [comment] 2024-07-08 11:44
duplicate of #981

**Comment by Kidswiss** [comment] 2024-07-23 12:03
Closing here in favour of #981

**Closed by Kidswiss** 2024-07-23 12:03 UTC
Labels: bug
