### ISSUE TITLE
Error when cleaning up: cannot add finalizer

### ISSUE THREAD

**Issue by ccremer** [k8up-io/k8up#402] opened 2021-03-17 15:51 UTC
## Describe the bug

K8up tries to add finalizers to deleted objects

## Additional context

Excerpt from log below: `Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"k8up.syn.tools/jobobserver\"}`

I think there should be some sort of guard clause that ignores adding finalizers when the object has a deletion timestamp.

## Logs

If applicable, add logs to help explain your problem.
```console
2021-03-17T15:38:48.620Z INFO controllers.Prune cleaning old job {"prune": "default/schedule-test-prune-kmfm7", "namespace": "default", "name": "schedule-test-prune-6msv6"}
2021-03-17T15:38:48.626Z INFO controllers.Prune cleaning old job {"prune": "default/schedule-test-prune-kmfm7", "namespace": "default", "name": "schedule-test-prune-6msv6"}
2021-03-17T15:38:48.632Z INFO controllers.Prune cleaning old job {"prune": "default/schedule-test-prune-kmfm7", "namespace": "default", "name": "schedule-test-prune-6msv6"}
2021-03-17T15:38:48.639Z INFO controllers.Prune cleaning old job {"prune": "default/schedule-test-prune-kmfm7", "namespace": "default", "name": "schedule-test-prune-6msv6"}
2021-03-17T15:38:48.644Z ERROR controller-runtime.manager.controller.job Reconciler error {"reconciler group": "batch", "reconciler kind": "Job", "name": "schedule-test-prune-6msv6", "namespace": "default", "error": "error updating resource: Job.batch \"schedule-test-prune-6msv6\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"k8up.syn.tools/jobobserver\"}"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/home/chris/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
/home/chris/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:99
2021-03-17T15:38:48.916Z ERROR controller-runtime.manager.controller.job Reconciler error {"reconciler group": "batch", "reconciler kind": "Job", "name": "schedule-test-prune-6msv6", "namespace": "default", "error": "error updating resource: Operation cannot be fulfilled on jobs.batch \"schedule-test-prune-6msv6\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/home/chris/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
/home/chris/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
/home/chris/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:99
```

## Expected behavior

This is probably just a cosmetic error.
Finalizers shouldn't be added to a deleted batchv1.job.

## To Reproduce

1. Commands
```bash
make e2e-test
kubectl apply -f config/samples/secrets.yaml
kubectl apply -f config/samples/k8up_v1alpha1_schedule.yaml 
# wait until enough objects are there so that cleaning kicks in. Observe mentioned error in the logs
```
Maybe there is a better reproduction step, e.g. just create a bunch of backups.

## Environment (please complete the following information):

- Image Version: v1.0.3
- K8s Version: v1.20
- K8s Distribution: KIND

**Comment by dimitraz** [comment] 2021-10-02 17:21
Hey, is this still relevant? If so I'd be happy to take a look at this as part of hacktoberfest :)

**Comment by Kidswiss** [comment] 2022-02-28 12:30
@ccremer have we ever encountered this again?

**Comment by ccremer** [comment] 2022-02-28 12:43
@Kidswiss I have not looked at K8up logs ever since, so I really don't know.

**Comment by Kidswiss** [comment] 2022-03-31 08:36
As discussed with @ccremer we're closing here, as we were not able to reproduce this issue.

**Closed by Kidswiss** 2022-03-31 08:36 UTC
Labels: bug
