### ISSUE TITLE
Pause Backup after pre definied time

### ISSUE THREAD

**Issue by SchoolGuy** [k8up-io/k8up#683] opened 2022-06-05 06:34 UTC
### Summary

**As** "a k8up admin"\
**I want** "to limit the time backups are being done"\
**So that** "I am able to effectively manage the usage of my storage"

### Context

I have two rather large volumes to backup with multiple TiB. Since I am a home user I don't have a dedicated dark fiber around to connect my two locations but I need to go plain through the internet. That means here in Germany with a standard contract I can habe 50Mbit/s upload. This means my systems are busy for quite a while transfering this data. It would be nice if I could tell k8up to pause the backup during the time me and my users are using the application. During the night k8up can continue happily at a defined time.

### Implementation Ideas

Since the data in a volume snapshot shouldn't change after it was taken, one should be able to utilize this capability maybe?

**Comment by Kidswiss** [comment] 2022-06-10 07:45
Hi @SchoolGuy 

Thanks for your suggestion. But unfortunately, this looks like a very specific feature and I think it's not something that would fit into K8up.

But I can give you a suggestion how you could achieve the same functionality. You could create a schedule that starts the backup at the desired time. Then you could create a cronjob that deletes the backup spawned by the schedule at your desired time. That effectively kills the job. The great thing about [restic](https://restic.readthedocs.io/) (the underlying backup tool) is that it can resume aborted backups where it left of.

**Comment by SchoolGuy** [comment] 2022-06-10 08:06
@Kidswiss That is good enough for me. Do you think it is worth to document this in your documentation somewhere. If yes I will happily contribute this once I got it working. If no, I would close the issue.

**Comment by Kidswiss** [comment] 2022-06-10 08:17
@SchoolGuy Sure if you're willing to write up something just open a PR. It should probably go into the "How-to guides" section.

**Comment by SchoolGuy** [comment] 2022-08-14 15:17
Update: Next week I will get started creating the long running backups and thus will experiment with this.

**Comment by SchoolGuy** [comment] 2022-08-15 12:05
@Kidswiss It turns out you maybe have a cheap way to integrate this after all.

If I understand the [k8s docs](https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup) correctly, there is the feature called `activeDeadlineSeconds` which would be pretty useful. You correctly pointed out that restic can continue backups where it was aborted. This would mean that we could have a guaranteed window where the backup runs. The current solution I am beginning to research is not very "clean" in the way that I either need to pass credentials via a secret and then run kubectl commands (via a CronJob) or I need to create a controller in Golang (which would essentially be the solution you could then integrate).

Especially since you have #581 & #399 I believe this is a duplicate.

**Comment by Kidswiss** [comment] 2022-08-15 13:01
@SchoolGuy: yeah I was thinking about the `activeDeadlineSeconds`, too. But when the job exceeds the deadline it will terminate with a `failed` state.

> That is, the Job termination mechanisms activated with .spec.activeDeadlineSeconds and .spec.backoffLimit result in a permanent Job failure that requires manual intervention to resolve.

We currently rely on the failed state for the monitoring: https://github.com/k8up-io/k8up/blob/master/charts/k8up/templates/prometheus/prometheusrule.yaml#L41.

Which unfortunately makes supporting the `activeDeadlineSeconds` a bit more complicated.

**Comment by SchoolGuy** [comment] 2022-08-15 15:28
@Kidswiss Why is that a problem? A backup that exceeds the timeout window will either signal that the storage has grown in an unforseen way or that there are other infrastructure problems (like slow network speed). Thus a failed state is appropriate imho. If you can't complete the backups you need to either fine-tune your alerts to your specific use-case or you need to invest into better infrastructure. In cloud native environments you anyway have basically unlimited bandwith due to the cloud providers infrastructure.

**Comment by Kidswiss** [comment] 2022-08-16 06:35
@SchoolGuy but in your use case it would be completely fine if the backup isn't finished in the time you specified, right? So then for your use case you would get false positives...

**Comment by SchoolGuy** [comment] 2022-08-16 09:13
@Kidswiss Well yes it is fine but as said in my comment, then I need to cover my corner case with a silence for the alert. That of course is non-trivial but a single user should not be able define the feature for the majority of users. I would see the alert desired since I then have the signal for a big data transfer (which should not happen very often since restic is incremental).

**Comment by Kidswiss** [comment] 2022-08-16 10:45
@SchoolGuy Sounds fine to me. 

Is it okay for you if I close this as a duplicate of #399? We should have a bit of capacity soon, so that an engineer can have a look at this feature.

**Comment by SchoolGuy** [comment] 2022-08-16 10:46
@Kidswiss Yes that is a lovely outcome. If you need help for testing just ping me, I am willing to install a preview into my environment for such purposes.

**Comment by Kidswiss** [comment] 2022-08-16 10:53
Great! I'm closing here. For more questions or feedback please follow #399.

**Closed by Kidswiss** 2022-08-16 10:53 UTC
Labels: enhancement
