### ISSUE TITLE
How to add insecureSkipTLSVerify=true for S3 bucket connection in K8up backup.yaml resource?

### ISSUE THREAD

**Issue by vistasunil** [k8up-io/k8up#882] opened 2023-08-15 14:21 UTC
### Description

Hello Team,

Provided [backup.yaml](https://github.com/k8up-io/k8up/blob/master/docs/modules/ROOT/examples/tutorial/backup.yaml) example file including K8up documentation, doesn't mentions anything about enabling insecureSkipTLSVerify=true flag for connecting to S3 buckets:

I am blocked due to this. Is there any way we can achieve the same?
If anyone knows, then kindly share the details.

Thanks & Regards,
Sunil Kumar

### Expected Behavior

Enabling insecure TLS while accessing S3 backup buckets should be allowed through K8up Kubernetes backup object.

### Version of K8up

2.7.1

### Version of Kubernetes

v1.24

### Distribution of Kubernetes

Rancher

**Comment by Kidswiss** [comment] 2023-08-16 06:30
Hi @vistasunil 

I'm closing this as a duplicate of https://github.com/k8up-io/k8up/issues/792.

**Closed by Kidswiss** 2023-08-16 06:30 UTC
Labels: bug
